CoreMVCModelSending_0/Models/Category.cs
namespace CoreMVCModelSending_0.Models
{
    public class Category
    {
        public string CategoryName { get; set; }
        public string Description { get; set; }

    }
}

CoreMVCModelSending_0/Models/Egitmen.cs
namespace CoreMVCModelSending_0.Models
{
    public class Egitmen
    {
        public string Isim { get; set; }
        public string SoyIsim { get; set; }

    }
}

CoreMVCModelSending_0/Models/ErrorViewModel.cs
namespace CoreMVCModelSending_0.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreMVCModelSending_0/Models/Product.cs
namespace CoreMVCModelSending_0.Models
{
    public class Product
    {
       
        public string ProductName { get; set; }
        public decimal UnitPrice { get; set; }

    }
}

CoreMVCModelSending_0/Controllers/CategoryController.cs
using CoreMVCModelSending_0.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreMVCModelSending_0.Controllers
{
    public class CategoryController : Controller
    {
        //Bir Category Class'i yaratın (İcinde CategoryName ve Description Property'leri olsun). Sonra GetCategory action'inda instance'i alınmıs bir Category'i ilgili View'da kullanıcıya ismi ve Acıklamasıyla gösterin (table seklinde)
        public IActionResult GetCategory()
        {
            Category c = new()
            {
                CategoryName = "Tatlılar",
                Description = "Test verisidir"
            };
            return View(c);
        }

        //Asagıdaki Action'da parametremiz program.cs'deki URL patternimizin parametre kısmına uymadıgı icin parametreye degeri slash ile degil querystring yöntemiyle (?a=2 seklinde) gönderebiliriz... 


        public IActionResult Index(int a)
        {
            return View();
        }


       
        public IActionResult CreateCategory()
        {
            //Biz eger BackEnd'den Front End'e bir model göndermiyorsak..Ama buna ragmen Front End sanki bir model karsılıyormus gibi bir ifade kullandıysa anlayın ki bu sefer bu demektir ki Front End Back End'e bir model gönderiyor
            return View();
        }


        [HttpPost]
        public IActionResult CreateCategory(Category category)
        {
            
            return View();
        }


    }
}

CoreMVCModelSending_0/Controllers/EgitmenController.cs
using CoreMVCModelSending_0.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreMVCModelSending_0.Controllers
{
    public class EgitmenController : Controller
    {


        //Bir EgitmenListesi yaratarak EgitmenEkleme sistemi olusturmanızı istiyorum...Oncelikle kişi get yontemiyle EgitmenEkleme sayfasına girecek...Sonra post ile yazdıgı bilgilerin servera gönderilmesini saglayarak yaratılmak istenen egitmeni Egitmen listesine ekleyecek...Sonra bir de EgitmenleriGetir Action'i olacak...EgitmenleriGetir Action'inina girildiginde eklenmiş olan bütün egitmenlerin table'da listelenmesini istiyorum...

        static List<Egitmen> egitmenler = new();

      

        public IActionResult EgitmenEkle()
        {

            return View();
        }

        [HttpPost]
        public IActionResult EgitmenEkle(Egitmen egitmen)
        {
            egitmenler.Add(egitmen);
            return View();
        }

        public IActionResult EgitmenleriGetir()
        {
            return View(egitmenler);
        }
    }



}

CoreMVCModelSending_0/Controllers/ProductController.cs
using CoreMVCModelSending_0.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreMVCModelSending_0.Controllers
{
    public class ProductController : Controller
    {
        #region OnemliNotlar

        //Bir View metodunun farklı bir View döndürmesi ile Model göndermesi arasında fark vardır. Bu metodun overloadlarinden birinde acık bir şekilde bir string parametre tanımlaması yapıldıgından dolayı metodun object parametre alan bir overload'i olmasına ragmen ilgili Metot bir string argüman ile cagrılırsa string parametreli overload'i calısır...Onun object overload'ini calıstırmak icin string argümanı object'e acıkca cast etmeniz gerekir...Yani siz, nasıl olsa her şey object'e gidiyor diye o ilgili object parametreli overload'in calısacagını düsünmemelisiniz(Cünkü acıkca string parametresi olan bir overload daha vardır) Siz bu bilgiyi gözden kacırırsanız verdiginiz string argümanın veri göndermek oldugunu(ModelSending yöntemiyle) zannedersiniz ama aslında o isimde bir sayfa döndürme görevi yapılır...

        //Model Göndermek Front End'e göstermek istediginiz bilgileri Back End'den Front End'e yollamak veya Front End'den almak istediginiz verileri Front End'den Back End'e göndermenin bir yoludur...Eger bu bilgi string bir tipte yollanacak ise o zaman verisinin object'e cast edilerek argüman olarak verilmesi gerekir (Cünkü View metodunda acıkca string parametre alan bir overload vardır)


        //Bir Model gönderiliyorsa karsılanmak zorundadır...

        //Model'in karsılanması View sayfasında @model(buradaki kücük harfli m'ye dikkat ediniz) diyerek gönderdiginiz verinin orijinal tipini yazmanız sayesinde olur...Model karsılandıktan sonra o ilgili verinin gösterilmesini istiyorsanız ise karsıladıgınız Model'i artık cagırmanız gerekir...Bu da @Model(büyük M harfina dikkat ediniz) sayesinde olur...

        //Aslında bir ModelSending yöntemini ilkel tipler veya ilkel tip gibi davranan verilerde tercih etmeyiniz..Onlar daha cok hafif bir veri gönderme yontemi ile gonderilebilir
        #endregion
        public IActionResult Index()
        {
            return View(12);
        }

        public IActionResult Contact()
        {
            return View("Hello World" as object);
        }

        public IActionResult GetProducts()
        {

            List<Product> products = new List<Product>()
            {
               new(){ProductName ="Tadelle",UnitPrice = 20},
               new(){ProductName = "Cizi",UnitPrice = 30},
               new(){ProductName = "Biskrem",UnitPrice = 40},
            };

            return View(products);
        }
    }
}

CoreMVCModelSending_0/Controllers/SimulasyonController.cs
using Microsoft.AspNetCore.Mvc;

namespace CoreMVCModelSending_0.Controllers
{
    public class SimulasyonController : Controller
    {
        //Eger bir View metodu bir string argüman ile cagrılıyorsa artık icinde cagrıldıgı Action isminde bir View sayfası aramaz sizin ona verdiginiz string argüman isminde bir View sayfası arar...Ancak bilmelisiniz ki bir View'in bu sekilde kullanılması standart degildir...Cünkü biz View'ların Action isimleriyle denk düsmesini isteriz ki projemiz icerisinde barındırılan kodlar temiz bir şekilde gözüksün...

        //View metodu, icerisine bir argüman verilmeden cagrıldıgı zaman hangi ACtion icerisindeyse o Action ile aynı isimde Vİew döndürme görevine sahiptir...Ancak bir View metoduna explicit bir şekilde(acıkca) string tipte bir argüman verilirse o zaman icinde bulundugu Action ismi neyse o isimde bir View'i döndürmeye calısır

        public IActionResult Index()
        {
            return View("Deneme");
        }
    }
}

CoreMVCModelSending_0/Views/Category/CreateCategory.cshtml
@model Category


<form asp-controller="Category" asp-action="CreateCategory" method="post">

    <div>
        <input type="text" asp-for="CategoryName" placeholder="Lutfen kategori ismi giriniz" class="form-control" />
    </div>

    <br />
    <div>
        <input type="text" asp-for="Description" placeholder="Lutfen acıklama giriniz" class="form-control"/>
    </div>


    @* <button class="btn btn-primary">Ekle</button> *@

    <input type="submit" class="btn btn-primary" value =Ekle /> 

</form>

CoreMVCModelSending_0/Views/Category/GetCategory.cshtml
@model Category


<table class="table table-hover">

    <thead>
        <tr>
            <th>Kategori Ismi</th>
            <th>Acıklama</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.CategoryName</td>
            <td>@Model.Description</td>
        </tr>
    </tbody>

</table>

CoreMVCModelSending_0/Views/Category/Index.cshtml
<h1>Hello World</h1>

CoreMVCModelSending_0/Views/Egitmen/EgitmenEkle.cshtml
@model Egitmen


<a class="btn btn-primary" asp-controller="Egitmen" asp-action="EgitmenleriGetir">Egitmenleri görüntüle</a>

<form asp-controller="Egitmen" asp-action="EgitmenEkle" method="post">

    <div>
        <input type="text" asp-for="Isim" placeholder="Isim giriniz" />
    </div>
    <br /> 
    <div>
        <input type="text" asp-for="SoyIsim" placeholder="Soyisim giriniz" />
    </div>

    <button>

        Ekle
    </button>


   

</form>

CoreMVCModelSending_0/Views/Egitmen/EgitmenleriGetir.cshtml
@model List<Egitmen>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Isim</th>
                <th>SoyIsim</th>
            </tr>
        </thead>

        <tbody>
        @foreach (Egitmen item in Model)
        {
            <tr>
                <td>@item.Isim</td>
                <td>@item.SoyIsim</td>
            </tr>
        }
    </tbody>
    </table>

CoreMVCModelSending_0/Views/Egitmen/Index.cshtml
@model int


<h1>@Model</h1>

CoreMVCModelSending_0/Views/Product/Contact.cshtml
@model string

<h2>  @Model   </h2>

CoreMVCModelSending_0/Views/Product/GetProducts.cshtml
@model List<Product>


    <table class="table table-hover">
        <thead>
            <tr>
                <th>Isim</th>
                <th>Fiyat</th>
            </tr>
        </thead>

        <tbody>
            @foreach (Product item in Model)
        {
            <tr>
                <td>@item.ProductName</td>
                <td>@item.UnitPrice</td>
            </tr>
        }



        </tbody>



    </table>

CoreMVCModelSending_0/Views/Product/Index.cshtml
@model int 


<!--Modelimizi karsıladık (GÖnderdiginiz verinin unutmayın ki gönderilecegi yerde hep karsılanması gerekir-->



<h2>  @Model </h2>

CoreMVCModelSending_0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreMVCModelSending_0</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoreMVCModelSending_0.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreMVCModelSending_0</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CoreMVCModelSending_0 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CoreMVCModelSending_0/Views/Simulasyon/Deneme.cshtml
<h1>Deneme</h1>

CoreMVCModelSending_0/Views/Simulasyon/Index.cshtml
<h1>Simulasyon</h1>